# Generated by Django 3.2.16 on 2023-01-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_page',
            old_name='Gender',
            new_name='gender',
        ),
    ]
