# Generated by Django 3.2.16 on 2023-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_quesmodel_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
                ('pswrepeat', models.CharField(max_length=100)),
            ],
        ),
    ]
