# Generated by Django 3.2.16 on 2023-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_signupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=100)),
                ('drpleavetypele', models.CharField(max_length=100)),
                ('drpapplyingtyp', models.CharField(max_length=100)),
                ('Noofdays', models.CharField(max_length=100)),
                ('todate', models.CharField(max_length=150)),
                ('fromdate', models.CharField(max_length=150)),
                ('mobileno', models.CharField(max_length=150)),
            ],
        ),
    ]
