# Generated by Django 3.2.16 on 2023-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_attendmodel_noofdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendmodel',
            name='Noofdays',
            field=models.IntegerField(),
        ),
    ]
