# Generated by Django 3.2.16 on 2023-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_attendmodel_noofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendmodel',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
