# Generated by Django 3.2.16 on 2023-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_attendmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendmodel',
            name='status',
            field=models.CharField(default='Waiting', max_length=150),
        ),
    ]
